import type { MobileConsoleSnapshot } from "./mobile-console-types";

const AGENT_DEFAULTS = [
  { id: "supervisor",             labelJa: "しきしま",    color: "#a371f7", category: "顔・管制塔" },
  { id: "hermes_worker",          labelJa: "Hermes Core", color: "#58a6ff", category: "心臓・脳" },
  { id: "ichikishima_reviewer",   labelJa: "いちきしま",  color: "#3fb950", category: "審判" },
  { id: "approval_guardian",      labelJa: "しずめ",      color: "#fb923c", category: "ブレーキ" },
  { id: "audit_keeper",           labelJa: "しるべ",      color: "#39d353", category: "記録と道標" },
  { id: "memory_curator",         labelJa: "つむぐ",      color: "#f778ba", category: "記憶・文脈" },
  { id: "visualization_observer", labelJa: "しるべ",      color: "#79c0ff", category: "記録と道標" },
  { id: "suppressive_agent",      labelJa: "しずめ",      color: "#f85149", category: "ブレーキ" },
  { id: "research_agent",         labelJa: "むすび",      color: "#d29922", category: "接続と編成" },
  { id: "execution_planner",      labelJa: "むすび",      color: "#8b949e", category: "接続と編成" },
].map((a) => ({
  ...a,
  enabled: false as const,
  dryRunOnly: true as const,
  requiresUserApproval: true as const,
  autoRun: false as const,
  autoApprove: false as const,
}));

/** Safe static default snapshot — aligned with Phase 30→45 state. */
export const MOBILE_CONSOLE_DEFAULT_SNAPSHOT: MobileConsoleSnapshot = {
  decision: "HOLD",
  execution: "disabled",
  productionReady: false,
  rawValuesReported: false,
  level3: "not_approved",
  robotMotion: "HOLD",
  appStatus: "initialized",
  phase: "iphone_private_console_phase_2c",
  b3Progress: {
    current: 5,
    required: 5,
    nextSession: "Level 3-A Session 005",
    timingRule: "human_go_required",
    rustDeskDeprecated: true,
    recentSessions: [
      { id: "L3-A Session 004", result: "PASS_WITH_TIMING_CAVEAT", date: "05-17" },
      { id: "L3-A Session 003", result: "STOP",                    date: "05-17" },
      { id: "L3-A Session 002", result: "STOP",                    date: "05-17" },
      { id: "L3-A Session 001", result: "STOP",                    date: "05-17" },
      { id: "B3 5/5",           result: "CLEAN_B3_PASS",           date: "05-16" },
    ],
  },
  pushReadiness: {
    branch: "main",
    headShort: "808a393",
    originMainShort: "7bc2526",
    commitsAhead: 1,
    stagedFiles: 0,
    dirtyTracked: 0,
    recommendation: "push_go_pending",
  },
  agentTeam: {
    schedulerEnabled: false,
    agents: AGENT_DEFAULTS,
    blockerCount: 0,
    warningCount: 0,
  },
  auditSummary: {
    approvalQueueCount: 0,
    auditLogCountLabel: "≈40",
    memoryCandidateCount: 5,
    recentEvents: [
      { time: "02:17", event: "Phase 20→30 COMPLETE_PASS_WITH_CAVEAT accepted",           type: "pass"   },
      { time: "02:10", event: "Session 004 PASS_WITH_CAVEAT — iPhone observation done",   type: "pass"   },
      { time: "01:55", event: "fix: windows installer non-blocking (7f98c78) pushed",     type: "commit" },
      { time: "01:40", event: "Session 003 HOLD — installer blocked observation",         type: "stop"   },
      { time: "01:20", event: "fix: hermes windows installer classifier (060f67c)",       type: "commit" },
    ],
  },
  stopHistory: [
    {
      sessionId: "L3-A-Session-003",
      stopType: "windows_manual_installer_required",
      date: "2026-05-17 01:46",
      classified: true,
      remediated: true,
      note: "Windows installer blocked iPhone observation. Fix 7f98c78 makes it non-blocking.",
    },
    {
      sessionId: "L3-A-Session-001",
      stopType: "unexpected_external_operation_appeared",
      date: "2026-05-17 00:15",
      classified: true,
      remediated: true,
      note: "NousResearch Hermes Installer appeared. Option B caveat policy established.",
    },
  ],
  generatedAt: "2026-05-17T02:17:00+09:00",
  dataSource: "static_phase1",
  komashikiState: "PUSH_WAITING",
  caveats: ["windows_manual_installer_required_non_blocking"],
  nextHumanAction: "push GO for roadmap docs → 30→45% phase planning",
  phaseProgress: "30% COMPLETE_PASS_WITH_CAVEAT",
  currentSession: "Session 004 PASS_WITH_CAVEAT",
};
