import type { MobileConsoleSnapshot } from "./mobile-console-types";

const AGENT_DEFAULTS = [
  { id: "supervisor",             labelJa: "しきしま",    color: "#a371f7", category: "顔・管制塔" },
  { id: "hermes_worker",          labelJa: "Hermes Core", color: "#58a6ff", category: "心臓・脳" },
  { id: "ichikishima_reviewer",   labelJa: "いちきしま",  color: "#3fb950", category: "審判" },
  { id: "approval_guardian",      labelJa: "しずめ",      color: "#fb923c", category: "ブレーキ" },
  { id: "audit_keeper",           labelJa: "しるべ",      color: "#39d353", category: "記録と道標" },
  { id: "memory_curator",         labelJa: "つむぐ",      color: "#f778ba", category: "記憶・文脈" },
  { id: "visualization_observer", labelJa: "しるべ",      color: "#79c0ff", category: "記録と道標" },
  { id: "suppressive_agent",      labelJa: "しずめ",      color: "#f85149", category: "ブレーキ" },
  { id: "research_agent",         labelJa: "むすび",      color: "#d29922", category: "接続と編成" },
  { id: "execution_planner",      labelJa: "むすび",      color: "#8b949e", category: "接続と編成" },
].map((a) => ({
  ...a,
  enabled: false as const,
  dryRunOnly: true as const,
  requiresUserApproval: true as const,
  autoRun: false as const,
  autoApprove: false as const,
}));

/** Safe static default snapshot for Phase 2B. */
export const MOBILE_CONSOLE_DEFAULT_SNAPSHOT: MobileConsoleSnapshot = {
  decision: "HOLD",
  execution: "disabled",
  productionReady: false,
  rawValuesReported: false,
  level3: "not_approved",
  robotMotion: "HOLD",
  appStatus: "initialized",
  phase: "iphone_private_console_phase_2b_ipc",
  b3Progress: {
    current: 4,
    required: 5,
    nextSession: "Session-009",
    timingRule: "window_start_plus_30_seconds",
    rustDeskDeprecated: true,
    recentSessions: [
      { id: "Session-007", result: "CLEAN_B3_PASS",           date: "05-14" },
      { id: "Session-006", result: "CLEAN_B3_PASS",           date: "05-14" },
      { id: "Session-008", result: "PASS_WITH_TIMING_CAVEAT", date: "05-15" },
      { id: "Session-005", result: "CLEAN_B3_PASS",           date: "05-14" },
      { id: "Session-003", result: "CLEAN_B3_PASS",           date: "05-15" },
      { id: "Session-002", result: "STOP",                    date: "05-15" },
    ],
  },
  pushReadiness: {
    branch: "main",
    headShort: "a668137",
    originMainShort: "a668137",
    commitsAhead: 0,
    stagedFiles: 0,
    dirtyTracked: 0,
    recommendation: "nothing_to_push",
  },
  agentTeam: {
    schedulerEnabled: false,
    agents: AGENT_DEFAULTS,
    blockerCount: 0,
    warningCount: 0,
  },
  auditSummary: {
    approvalQueueCount: 0,
    auditLogCountLabel: "≈15",
    memoryCandidateCount: 3,
    recentEvents: [
      { time: "11:50", event: "canonical agent naming v2 docs aligned",              type: "docs"   },
      { time: "11:40", event: "Phase 2B-2 localhost GET server module committed",    type: "commit" },
      { time: "11:30", event: "Phase 2B-1 IPC redacted snapshot pushed",            type: "commit" },
      { time: "11:20", event: "Phase 2B design docs committed",                      type: "commit" },
      { time: "11:07", event: "Session-009 STOP (外部インストーラー検出)",             type: "stop"   },
    ],
  },
  stopHistory: [
    {
      sessionId: "shikishima-session-2026-05-15-009",
      stopType: "unexpected_external_operation_appeared",
      date: "2026-05-15 11:07",
      classified: true,
      remediated: false,
      note: "NousResearch Hermes Installer が表示。別Taskで調査予定。",
    },
    {
      sessionId: "shikishima-session-2026-05-15-002",
      stopType: "raw_value_visible",
      date: "2026-05-15 21:17",
      classified: true,
      remediated: true,
      note: "APIキープレフィックスが表示。fix 48e2f78 で解消。",
    },
  ],
  generatedAt: "2026-05-15T00:00:00+09:00",
  dataSource: "static_phase1",
};
