// Research Report Generator
// Formats XS-AUTO findings into a single markdown article for permanent memory.
// Output goes to Discord (しきしまレポート) and Obsidian (40_Research/).

export interface ResearchReportInput {
  date: string; // YYYY-MM-DD
  title: string;
  topics: string[];
  findings: string; // markdown body (pre-formatted findings text)
  keyPoints: string[];
  sources: string[];
  relevance?: string;
  gateId?: string; // e.g. "XS-AUTO-03"
}

export interface ResearchReport {
  filename: string; // YYYY-MM-DD_slug.md
  markdownContent: string;
  discordContent: string; // truncated to 2000 chars for Discord
  title: string;
  date: string;
}

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, "-")
    .slice(0, 60);
}

export function generateResearchReport(input: ResearchReportInput): ResearchReport {
  const { date, title, topics, findings, keyPoints, sources, relevance, gateId } = input;

  const frontmatter = [
    "---",
    `date: ${date}`,
    `title: "${title}"`,
    `topics: [${topics.map((t) => `"${t}"`).join(", ")}]`,
    `source: ${gateId ?? "XS-AUTO"}`,
    `xacc: HOLD`,
    `rawValuesReported: false`,
    "---",
  ].join("\n");

  const keyPointsSection =
    keyPoints.length > 0
      ? `\n## Key Points\n\n${keyPoints.map((p) => `- ${p}`).join("\n")}`
      : "";

  const relevanceSection = relevance
    ? `\n## Shikishima への関連性\n\n${relevance}`
    : "";

  const sourcesSection =
    sources.length > 0
      ? `\n## Sources\n\n${sources.map((s) => `- ${s}`).join("\n")}`
      : "";

  const markdownContent = [
    frontmatter,
    "",
    `# ${title}`,
    "",
    `> ${date} | ${gateId ?? "XS-AUTO"} | read-only research`,
    "",
    "## Findings",
    "",
    findings,
    keyPointsSection,
    relevanceSection,
    sourcesSection,
    "",
    "---",
    "*Generated by Shikishima research pipeline*",
    "*rawValuesReported: false / XACC: HOLD*",
  ]
    .filter((s) => s !== undefined)
    .join("\n");

  // Discord version: no frontmatter, truncated to 2000 chars
  const discordHeader = `**${title}** — ${date}\n\n`;
  const discordBody = findings.slice(0, 1800 - discordHeader.length);
  const discordContent = discordHeader + discordBody + (findings.length > 1800 ? "\n\n_[続きは Obsidian を参照]_" : "");

  const filename = `${date}_${slugify(title)}.md`;

  return { filename, markdownContent, discordContent, title, date };
}
